apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f myapp-compose.yaml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: myapp
  name: myapp
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 5000
  selector:
    io.kompose.service: myapp
